### ISSUE TITLE
Product Page

### ISSUE THREAD

**Issue by Elginz** [Elginz/SMart#3]
Use edit.js and edit.ejs 

![Image](https://github.com/user-attachments/assets/73e30b90-bc6b-4d20-abfb-11315c61fefb)

**Comment by Elginz** [comment]
![Image](https://github.com/user-attachments/assets/682d228a-471f-4a12-9b36-0b010f589215)

**Comment by rovalf** [comment]
Fix the to allow the 4 images to be uploaded

**Comment by Elginz** [comment]
- Can only upload 2 images, 

- must have multiple options for transactions
