### ISSUE TITLE
Product listing page

### ISSUE THREAD

**Issue by Elginz** [Elginz/SMart#4]
To add a new product. 

Use the edit.ejs and author.js file as reference

![Image](https://github.com/user-attachments/assets/e2af30ff-8d77-40d5-94d5-c982f1438e4e)

**Comment by Elginz** [comment]
fix the image issues after ellen has completed the rest

**Comment by Elginz** [comment]
uploading 2 images produces 1 jpg

**Comment by rovalf** [comment]
Fix the image upload of 4 images
